fail_fast: false

files: |
  (?x)(
    ^src/django_jsonrpc/.*$|
  )

exclude: |
  (?x)(
      ^docs/|
      ^migrations/|
  )

default_stages: [pre-commit]
minimum_pre_commit_version: "3.2.0"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: detect-private-key

  # Linter & Format.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
      