"""Abstract Base Classes for the Vector Store components."""
from abc import ABC, abstractmethod
from typing import Any, Dict, List, Set


class EmbeddingAdapter(ABC):
    """Abstract base class for embedding providers."""

    def __init__(self, model_name: str, **kwargs: Any):
        self.model_name = model_name

    @property
    @abstractmethod
    def embedding_dimension(self) -> int:
        """The dimension of the embeddings generated by the model."""
        raise NotImplementedError

    @abstractmethod
    def get_embeddings(self, texts: List[str]) -> List[List[float]]:
        """
        Generates embeddings for a list of texts.

        Args:
            texts: A list of strings to embed.

        Returns:
            A list of embedding vectors.
        """
        raise NotImplementedError


class VectorDBAdapter(ABC):
    """Abstract base class for vector database providers."""

    @abstractmethod
    def initialize(
        self, collection_name: str, embedding_dimension: int, metric: str = "cosine"
    ):
        """
        Initializes the database and ensures the collection is ready.

        Args:
            collection_name: The name of the collection to use.
            embedding_dimension: The dimension of the vectors to be stored.
            metric: The distance metric for vector search (e.g., 'cosine').
        """
        raise NotImplementedError

    @abstractmethod
    def upsert(self, documents: List[Dict[str, Any]]):
        """
        Inserts or updates multiple documents in the collection.

        Args:
            documents: A list of document dictionaries to insert or update.
        """
        raise NotImplementedError

    @abstractmethod
    def search(
        self, vector: List[float], limit: int, fields: Set[str]
    ) -> List[Dict[str, Any]]:
        """
        Performs a vector similarity search.

        Args:
            vector: The query vector.
            limit: The maximum number of results to return.
            fields: A set of field names to include in the results.

        Returns:
            A list of matching documents.
        """
        raise NotImplementedError

    @abstractmethod
    def get(self, id: str) -> Dict[str, Any] | None:
        """
        Retrieves a single document by its ID.
        """
        raise NotImplementedError

    @abstractmethod
    def count(self) -> int:
        """
        Returns the total number of documents in the collection.
        """
        raise NotImplementedError

    @abstractmethod
    def delete_one(self, id: str) -> int:
        """
        Deletes a single document by its ID.
        """
        raise NotImplementedError

    @abstractmethod
    def delete_many(self, ids: List[str]) -> int:
        """
        Deletes multiple documents by their IDs.
        """
        raise NotImplementedError
